import { z } from 'zod';

/**
 * 规划回退到规则占位的原因 / Why planning fell back to the rule-based stub.
 *
 * ★★ 为什么必须是码，不能继续把原因拼进 `model` 字段。
 *
 *   此前回退的唯一痕迹是 `plans.model` 里的一句中文：
 *
 *     stub:development（规则占位，未走 Agent：Agent 结束了但没有写出 apos-output.json）
 *
 *   它有三个问题，而三个都只在真出事的时候才显形：
 *
 *   1. 英文界面上它是一整句中文，混在「Generated by Project Agent」后面，
 *      读起来像模型名的一部分。
 *   2. 界面**无法**据此改变行为。回退计划是一份与需求无关的通用模板，
 *      而页面照样说「4 个任务会自动跑」「预计 625k tokens」「会自动开 PR」——
 *      那三句都是模板常量，不是这次工作的事实。想禁掉它们，前端只能去
 *      正则匹配那句随时会改的中文。
 *   3. 「怎么修」无从表达。缺凭证、Agent 没写出文件、产出格式不对，
 *      三者的下一步动作完全不同，而一句话里看不出是哪一种。
 *
 *   所以：界面读码决定怎么渲染、给哪个修复入口；`model` 里那句中文保留
 *   给日志与存量数据当兜底。**界面读码，日志读句子。**
 *
 * The UI must be able to *act* on a fallback — suppress the automation claims,
 * offer the right remedy — and it cannot do that against a prose sentence.
 */
export const PlanFallbackCode = z.enum([
  /** 调用方没给 orgId/projectId，挑不出规划 Agent（内部调用问题） */
  'no_scope',
  /** 项目里没有可用的规划 Agent */
  'no_agent',
  /** 挑中的 Agent 没在本进程注册 —— 通常是凭证缺失或运行时不可用 */
  'agent_unregistered',
  /** 运行时拒收这次派发 */
  'runtime_rejected',
  /** 派发出去了但这次执行没跑完（超时、中断） */
  'run_failed',
  /** Agent 正常结束，却没有写出约定的产出文件 */
  'output_missing',
  /** 产出文件不符合约定格式 */
  'output_invalid',
  /** 产出能解析，但计划本身不自洽（依赖成环、引用不存在的任务等） */
  'output_inconsistent',
  /** 其他异常 */
  'unexpected_error',
]);
export type PlanFallbackCode = z.infer<typeof PlanFallbackCode>;

export const PlanFallback = z.object({
  code: PlanFallbackCode,
  /**
   * 原始中文说明。
   *
   * ★ 保留它不是冗余：它带着码里放不下的细节（是哪个 Agent、
   *   zod 报了哪几个字段），日志与排查全靠这一句。界面只在
   *   认不出码的时候才回落到它。
   */
  reason: z.string(),
});
export type PlanFallback = z.infer<typeof PlanFallback>;

/**
 * 这次回退还值不值得让用户按原样批准。
 *
 * ★ 全部都不值得 —— 回退产出的是与需求无关的通用模板。
 *   留成函数而不是写死 false，是因为将来可能出现「部分回退」
 *   （比如只有工期估算退化），那时这里才是该分叉的地方。
 */
export function isPlanTrustworthy(fallback: PlanFallback | null): boolean {
  return fallback === null;
}
